In [58]:
import pandas as pd
from faker import Faker

users = pd.read_csv('New folder/user.csv')
companies = pd.read_csv('New folder/mycompanies.csv')

fake = Faker()

newUsers=users.drop(columns=['Subscription Plan','Renewal Status','Customer Support Interactions','Feedback/Ratings','Membership End Date'])
newUsers.rename(columns={'Name': 'name','Email Address' :'email','Date of Birth': 'Brithday','Membership Start Date':'createdAt'}, inplace=True)
newUsers['role'] = 'Customer'
newUsers['phone'] = [fake.numerify(text='+1 ### ### ####') for _ in range(len(newUsers))]
newUsers['city'] = [fake.city() for _ in range(len(newUsers))]
newUsers['street'] = [fake.street_address() for _ in range(len(newUsers))]  # شارع
newUsers['postcode'] = [fake.postcode() for _ in range(len(newUsers))] 
print(newUsers.columns)
print(newUsers)
newUsers.to_csv('Users.csv', index=False)

Index(['User ID', 'name', 'email', 'Username', 'Brithday', 'Gender',
       'Location', 'createdAt', 'Payment Information', 'Usage Frequency',
       'Purchase History', 'Favorite Genres', 'Devices Used',
       'Engagement Metrics', 'role', 'phone', 'city', 'street', 'postcode'],
      dtype='object')
      User ID              name                           email  \
0           1     Ronald Murphy      williamholland@example.com
1           2       Scott Allen             scott22@example.org
2           3  Jonathan Parrish            brooke16@example.org
3           4    Megan Williams         elizabeth31@example.net
4           5     Kathryn Brown  pattersonalexandra@example.org
...       ...               ...                             ...
2495     2496     Michael Lopez     williamsroberto@example.org
2496     2497   Matthew Woodard             lkaiser@example.com
2497     2498     Morgan Barnes        erikaholland@example.net
2498     2499    Gina Castaneda        reedcourtney@example.net
2499     2500    Mark Nicholson         martinisaac@example.net

                Username    Brithday  Gender          Location   createdAt  \
0         williamholland  1953-06-03    Male    Rebeccachester  2024-01-15
1                scott22  1978-07-08    Male     Mcphersonview  2024-01-07
2               brooke16  1994-12-06  Female         Youngfort  2024-04-13
3            elizabeth31  1964-12-22  Female      Feliciashire  2024-01-24
4     pattersonalexandra  1961-06-04    Male      Port Deborah  2024-02-14
...                  ...         ...     ...               ...         ...
2495     williamsroberto  1967-08-19    Male         Smithport  2024-01-25
2496             lkaiser  1980-10-23    Male         Ethanport  2024-03-03
2497        erikaholland  1972-03-31  Female  Alexandraborough  2024-02-09
2498        reedcourtney  1965-08-02  Female      Williammouth  2024-02-18
2499         martinisaac  1972-11-13  Female    Estradaborough  2024-01-28

     Payment Information Usage Frequency Purchase History Favorite Genres  \
0             Mastercard         Regular      Electronics     Documentary
1                   Visa         Regular      Electronics          Horror
2             Mastercard         Regular            Books          Comedy
3                   Amex         Regular      Electronics     Documentary
4                   Visa        Frequent         Clothing           Drama
...                  ...             ...              ...             ...
2495                Visa        Frequent      Electronics          Comedy
2496                Amex        Frequent            Books          Comedy
2497                Visa        Frequent      Electronics     Documentary
2498                Visa         Regular         Clothing          Comedy
2499                Visa         Regular            Books     Documentary

     Devices Used Engagement Metrics      role            phone  \
0        Smart TV             Medium  Customer  +1 933 362 0117
1      Smartphone             Medium  Customer  +1 095 385 6349
2        Smart TV                Low  Customer  +1 807 802 5772
3        Smart TV               High  Customer  +1 177 558 9166
4        Smart TV                Low  Customer  +1 395 309 0114
...           ...                ...       ...              ...
2495   Smartphone             Medium  Customer  +1 274 064 9278
2496     Smart TV             Medium  Customer  +1 769 232 8128
2497       Tablet                Low  Customer  +1 502 003 6543
2498   Smartphone               High  Customer  +1 148 675 0218
2499     Smart TV               High  Customer  +1 508 016 7111

                      city                         street postcode
0              South Craig     59043 Lopez Pines Apt. 975    37674
1     West Christopherland              30461 Miller Land    11501
2              Gailchester                038 Price Roads    51746
3               Patelville       2498 Lloyd Camp Apt. 490    22817
4              Anthonyland            152 Thompson Shores    98633
...                    ...                            ...      ...
2495           West Isabel  4359 Robinson Cliffs Apt. 127    17174
2496             Garyshire        946 Aaron Key Suite 742    50808
2497      South Jeffreyton   2713 Thomas Squares Apt. 599    49687
2498      East Danielville             7692 Taylor Canyon    79979
2499        West Lindatown   275 Kevin Villages Suite 514    91868

[2500 rows x 19 columns]